Misc Stein Fixes
osuosl-cookbooks/osl-openstack pull request #178
Opened 2020-11-18 18:48 UTC by ramereth

- Limit nova-metdata/placement-api to a single thread to workaround issue
- Edit the `apache2_install[openstack]` resource to match OSL standards

2020-11-18 23:55 UTC, detjensrobert requested changes
Should there be a Inspec test to verify that Apache has the correct settings set?

2020-11-19 00:01 UTC, ramereth commented
@detjensrobert I feel confident enough that the ChefSpec tests should coverge this.

2020-11-19 00:02 UTC, detjensrobert approved these changes
LGTM then

2020-11-19 00:04 UTC, ramereth commented
!bump patch openstack_stein

2020-11-19 00:04 UTC, merged

2020-11-19 00:04 UTC, osuosl-manatee commented
Jenkins has merged this PR into `master` and has automatically performed a patch-level version bump to v9.0.1.  Have a nice day!